#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 google-raffle contributors
set -eu
ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec java -jar "$ROOT_DIR/vendor/jixoo/target/jixoo64-0.3.0-cli.jar" "$@"
